#!/usr/bin/env bash
#
# process-sync.sh — pull the process spec forward into a consuming repo.
#
# Realizes the template+sync model of ADR-0001: a repo vendors a READ-ONLY copy of the
# process spec into its own docs/process/, pinned to a VERSION. Run from the CONSUMING
# repo's root directory.
#
# Usage:
#   process-sync.sh <process-repo-path>            # vendor/update the spec, leave changes unstaged for PR review
#   process-sync.sh <process-repo-path> --check    # CI: exit non-zero if the repo is behind (drift)
#
# Exit: 0 in sync / synced · 1 drift found (--check) · 2 could not run
#
# The spec is edited ONLY in the process repo. Never edit a vendored copy in docs/process/.
# Deps: bash, diff, sed, tr — no language runtime, deliberately.
set -euo pipefail

VENDOR_DIR="docs/process"          # where the vendored spec lands in the consumer (relative to CWD)
CONFIG="${VENDOR_DIR}/sync.config" # records the pinned process version

die() { printf 'process-sync: %s\n' "$1" >&2; exit 2; }

[ $# -ge 1 ] || die "usage: process-sync.sh <process-repo-path> [--check]"
PROCESS="${1%/}"
MODE="sync"
[ "${2:-}" = "--check" ] && MODE="check"
[ "${2:-}" = "" ] || [ "${2:-}" = "--check" ] || die "unknown argument: ${2}"

[ -f "${PROCESS}/VERSION" ]       || die "no VERSION at ${PROCESS} — is that the process repo?"
[ -f "${PROCESS}/sync/manifest" ] || die "no sync/manifest at ${PROCESS}"
[ -d "${PROCESS}/spec" ]          || die "no spec/ at ${PROCESS}"

PROCESS_VERSION="$(tr -d '[:space:]' < "${PROCESS}/VERSION")"

# Read the manifest (skip comments/blanks) into an array.
manifest=()
while IFS= read -r line; do
  line="${line%%#*}"; line="$(printf '%s' "$line" | tr -d '[:space:]')"
  [ -n "$line" ] && manifest+=("$line")
done < "${PROCESS}/sync/manifest"
[ ${#manifest[@]} -gt 0 ] || die "manifest is empty"

pinned_version() { [ -f "$CONFIG" ] && sed -n 's/^PROCESS_VERSION=//p' "$CONFIG" | head -n1 || true; }

if [ "$MODE" = "check" ]; then
  drift=0
  pv="$(pinned_version)"
  if [ "$pv" != "$PROCESS_VERSION" ]; then
    printf 'DRIFT: pinned version "%s" != process version "%s"\n' "${pv:-<none>}" "$PROCESS_VERSION" >&2
    drift=1
  fi
  for f in "${manifest[@]}"; do
    if [ ! -f "${VENDOR_DIR}/${f}" ]; then
      printf 'DRIFT: missing vendored file %s\n' "${VENDOR_DIR}/${f}" >&2; drift=1; continue
    fi
    if ! diff -q "${PROCESS}/spec/${f}" "${VENDOR_DIR}/${f}" >/dev/null 2>&1; then
      printf 'DRIFT: %s differs from process spec/%s\n' "${VENDOR_DIR}/${f}" "$f" >&2; drift=1
    fi
  done
  if [ "$drift" -ne 0 ]; then
    printf 'process-sync: this repo is BEHIND the process spec — run `process-sync.sh %s` and review.\n' "$PROCESS" >&2
    exit 1
  fi
  printf 'process-sync: in sync with process %s — no drift.\n' "$PROCESS_VERSION"
  exit 0
fi

# sync mode
mkdir -p "$VENDOR_DIR"
changed=0
for f in "${manifest[@]}"; do
  dest="${VENDOR_DIR}/${f}"
  mkdir -p "$(dirname "$dest")"
  if [ ! -f "$dest" ] || ! diff -q "${PROCESS}/spec/${f}" "$dest" >/dev/null 2>&1; then
    cp "${PROCESS}/spec/${f}" "$dest"; changed=$((changed+1)); printf '  updated %s\n' "$dest"
  fi
done

cat > "$CONFIG" <<EOF
# Generated by process-sync.sh — pins this repo to a process spec version.
# The files in this directory are VENDORED, READ-ONLY copies of the process spec.
# Do not edit them here; edit the spec in the process repo and re-run process-sync.sh.
PROCESS_VERSION=${PROCESS_VERSION}
EOF

if [ "$changed" -eq 0 ]; then
  printf 'process-sync: already at process %s — nothing to update.\n' "$PROCESS_VERSION"
else
  printf 'process-sync: synced %d file(s) to process %s. Changes are UNSTAGED — review them in your PR.\n' "$changed" "$PROCESS_VERSION"
fi
